### ISSUE TITLE
the seperated speech can't play

### ISSUE THREAD

**Issue by JayYang-Fdu** [zhr1201/deep-clustering#18]
I ran the audio_test.py in the Pycharm,and I got the warnning as follows:ComplexWarning: Casting complex values to real discards the imaginary part
  frame_out1 = np.fft.ifft(out1).astype(np.float64)
D:/Python/process/speechseperation/infer.py:192: ComplexWarning: Casting complex values to real discards the imaginary part
  frame_out2 = np.fft.ifft(out2).astype(np.float64)
D:/Python/process/speechseperation/infer.py:193: ComplexWarning: Casting complex values to real discards the imaginary part
  frame_mix = np.fft.ifft(out_mix).astype(np.float64)

 and the seperated speech can not play, I don't know why,  due to my model or the code? your prompt reply will be highly appreciated!!!

**Comment by zhr1201** [comment]
The warning is not a problem because the imaginary part should be very close to zero. Basically a audiofile(wav) is a stream of type short data (writing float should also work fine cause the python audio library does the implicit conversion for you). If you can't play the audio you probably should 1. plot the out_mix to see if the values are too large or too small 2. checkout the audiowrite API of librosa or scipy (which used for writing the audio file) to see if it is used correctly.

**Comment by JayYang-Fdu** [comment]
Thank you so much for your prompt reply！Are you Chinese?I'm Chinese!Could you please show the model you trained to me...and the size of the model I trained remains the same...is it normal?发自我的华为手机-------- 原始邮件 --------主题：Re: [zhr1201/deep-clustering] the seperated speech can't play (#18)发件人：Haoran Zhou 收件人：zhr1201/deep-clustering 抄送：Yangjie55 ,Author The warning is not a problem because the imaginary part should be very close to zero. Basically a audiofile(wav) is a stream of type short data (writing float should also work fine cause the python audio library does the implicit conversion for you). If you can't play the audio you probably should 1. plot the out_mix to see if the values are too large or too small 2. checkout the audiowrite API of librosa or scipy (which used for writing the audio file) to see if it is used correctly.

**Comment by zhr1201** [comment]
是啊，是中国人啊。但是这个代码两年前写的了，现在在外面工作，当时的模型在学校服务器上应该早就不在了，抱歉啊。。

**Comment by JayYang-Fdu** [comment]
嘿嘿 巧遇咯！这样啊...那我该叫你老哥了！我也是最近在做这个毕业设计、搞了很久了...差点从不会到放弃...可能是我数据集的问题...但是我也用了一下别人的模型、但是分离出来的声音就是无法播放...不知道为什么！心塞塞发自我的华为手机-------- 原始邮件 --------主题：Re: [zhr1201/deep-clustering] the seperated speech can't play (#18)发件人：Haoran Zhou 收件人：zhr1201/deep-clustering 抄送：Yangjie55 ,Author 是啊，是中国人啊。但是这个代码两年前写的了，现在在外面工作，当时的模型在学校服务器上应该早就不在了，抱歉啊。。

**Comment by zhr1201** [comment]
这个一般不会播放不了的，你看一下最后存语音的数组什么样子。一般只要把范围-1到1的数组，不管里面数字是怎么生成的，写道音频文件中都能够播放。

**Comment by zhr1201** [comment]
by the way你哪个学校什么专业的啊？本科毕设？

**Comment by JayYang-Fdu** [comment]
> by the way你哪个学校什么专业的啊？本科毕设？

对的，做的是本科毕设，我本科上海大学，做的题目是基于深度学习的语音信号分离...以前从来没接触过深度学习，唉眼看着要答辩了...心态不能崩hhh。那个数组我截的图如下：
![image](https://user-images.githubusercontent.com/48006476/55786041-13a3f180-5ae6-11e9-8d8c-a5007ae3fbe0.png)

这个是分离出audio_out1 数组    好像不在-1到1 之间。。。

**Comment by zhr1201** [comment]
这个看上去是在-1到1之间的，有些就算超过了也会clip掉的，应该是写wav的库版本和之前的有些不同。你看看那个模块（记得好像是librosa）音频读写的说明就行了

**Comment by JayYang-Fdu** [comment]
好嘞  谢谢！今天麻烦你啦！我往后有问题...还可以问你嘛...（捂脸）

**Comment by zhr1201** [comment]
可以的hhhhhh

**Comment by Yangjie55** [comment]
老大哥 我的微信：17701684692 你加我吧 嘿嘿  害羞 我太主动了hhh

**Comment by JayYang-Fdu** [comment]
嘿嘿 老哥 我又来了。。。那个timit数据集 要转换成能播放的wav格式再训练吗？ 因为我下载的这个timit数据集 无法播放 我查了一下 说里面的数据是sphere格式的。。

**Comment by zhr1201** [comment]
是的，需要先转成wav




On 04/10/2019 10:08, Yangjie55 wrote:

嘿嘿 老哥 我又来了。。。那个timit数据集 要转换成能播放的wav格式再训练吗？ 因为我下载的这个timit数据集 无法播放 我查了一下 说里面的数据是sphere格式的。。

**Comment by JayYang-Fdu** [comment]
好嘞 谢谢哥

**Comment by Yangjie55** [comment]
哥  我又来了。。。希望没打扰到你。。。
 就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing)    一个一个产生好像也可以，也不是很多。。。这个方法对吗?

**Comment by zhr1201** [comment]
是的，我当时就是一个个产生的




On 04/10/2019 16:22, Yangjie55 wrote:

哥 我又来了。。。希望没打扰到你。。。
就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing) 一个一个产生好像也可以，也不是很多。。。这个方法对吗?

**Comment by JayYang-Fdu** [comment]
好嘞！ 明白啦！谢谢哥！

**Comment by yzy0729** [comment]
> 好嘞  谢谢！今天麻烦你啦！我往后有问题...还可以问你嘛...（捂脸）



> by the way你哪个学校什么专业的啊？本科毕设？
> 
> 对的，做的是本科毕设，我本科上海大学，做的题目是基于深度学习的语音信号分离...以前从来没接触过深度学习，唉眼看着要答辩了...心态不能崩hhh。那个数组我截的图如下：
> 
> 这个是分离出audio_out1 数组    好像不在-1到1 之间。。。

巧了同学，我今年毕设也是做的语音分离

**Comment by JayYang-Fdu** [comment]
> 是的，我当时就是一个个产生的
> 
> 
> 
> 
> On 04/10/2019 16:22, Yangjie55 wrote:
> 
> 哥 我又来了。。。希望没打扰到你。。。
> 就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing) 一个一个产生好像也可以，也不是很多。。。这个方法对吗?
> 
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.

哥，抱歉又要打扰你啦。这段时间我的程序已经能够分离出语音啦，但是我有几个问题，能请教你一下嘛：
1.因为聚类不是无监督学习嘛，那为啥这个需要创建这个lstm的神经网络来训练呢？（原论文只是随口提了一下深度学习获得嵌入特征能够使分离更高效，这里就不是很明白。。）还有就是那个spectral embedding不是很明白是啥意思，有点不太明白唉
2.还有一个问题就是，我用的数据集是timit数据集嘛，是每一个说话者单独分开的，但是我看原论文里面，作者们好像是创建了混合语音来训练的吧。

**Comment by yzy0729** [comment]
> 是的，我当时就是一个个产生的
> On 04/10/2019 16:22, Yangjie55 wrote:
> 哥 我又来了。。。希望没打扰到你。。。
> 就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing) 一个一个产生好像也可以，也不是很多。。。这个方法对吗?
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 哥，抱歉又要打扰你啦。这段时间我的程序已经能够分离出语音啦，但是我有几个问题，能请教你一下嘛：
> 1.因为聚类不是无监督学习嘛，那为啥这个需要创建这个lstm的神经网络来训练呢？（原论文只是随口提了一下深度学习获得嵌入特征能够使分离更高效，这里就不是很明白。。）还有就是那个spectral embedding不是很明白是啥意思，有点不太明白唉
> 2.还有一个问题就是，我用的数据集是timit数据集嘛，是每一个说话者单独分开的，但是我看原论文里面，作者们好像是创建了混合语音来训练的吧。

同学，我也是毕设做语音分离的，想问一下你的tensorflow用的什么版本的？是GPU版的吗？为什么我用GPU版本的报错。

**Comment by JayYang-Fdu** [comment]
> 是的，我当时就是一个个产生的
> On 04/10/2019 16:22, Yangjie55 wrote:
> 哥 我又来了。。。希望没打扰到你。。。
> 就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing) 一个一个产生好像也可以，也不是很多。。。这个方法对吗?
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 哥，抱歉又要打扰你啦。这段时间我的程序已经能够分离出语音啦，但是我有几个问题，能请教你一下嘛：
> 1.因为聚类不是无监督学习嘛，那为啥这个需要创建这个lstm的神经网络来训练呢？（原论文只是随口提了一下深度学习获得嵌入特征能够使分离更高效，这里就不是很明白。。）还有就是那个spectral embedding不是很明白是啥意思，有点不太明白唉
> 2.还有一个问题就是，我用的数据集是timit数据集嘛，是每一个说话者单独分开的，但是我看原论文里面，作者们好像是创建了混合语音来训练的吧。
> 
> 同学，我也是毕设做语音分离的，想问一下你的tensorflow用的什么版本的？是GPU版的吗？为什么我用GPU版本的报错。

tensorflow-gpu=1.2.0 cuda 8.0    cudnn 安装好相应版本就好了

**Comment by sTarAnna** [comment]
> > 是的，我当时就是一个个产生的
> > On 04/10/2019 16:22, Yangjie55 wrote:
> > 哥 我又来了。。。希望没打扰到你。。。
> > 就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing) 一个一个产生好像也可以，也不是很多。。。这个方法对吗?
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 哥，抱歉又要打扰你啦。这段时间我的程序已经能够分离出语音啦，但是我有几个问题，能请教你一下嘛：
> 1.因为聚类不是无监督学习嘛，那为啥这个需要创建这个lstm的神经网络来训练呢？（原论文只是随口提了一下深度学习获得嵌入特征能够使分离更高效，这里就不是很明白。。）还有就是那个spectral embedding不是很明白是啥意思，有点不太明白唉
> 2.还有一个问题就是，我用的数据集是timit数据集嘛，是每一个说话者单独分开的，但是我看原论文里面，作者们好像是创建了混合语音来训练的吧。

1. 他这个是有监督的训练。embedding就是每个时频单元的D维特征.
2. datagenerator.py就是用来将多个单人混合成多个双人的。

**Comment by sTarAnna** [comment]
> > 是的，我当时就是一个个产生的
> > On 04/10/2019 16:22, Yangjie55 wrote:
> > 哥 我又来了。。。希望没打扰到你。。。
> > 就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing) 一个一个产生好像也可以，也不是很多。。。这个方法对吗?
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> > 哥，抱歉又要打扰你啦。这段时间我的程序已经能够分离出语音啦，但是我有几个问题，能请教你一下嘛：
> > 1.因为聚类不是无监督学习嘛，那为啥这个需要创建这个lstm的神经网络来训练呢？（原论文只是随口提了一下深度学习获得嵌入特征能够使分离更高效，这里就不是很明白。。）还有就是那个spectral embedding不是很明白是啥意思，有点不太明白唉
> > 2.还有一个问题就是，我用的数据集是timit数据集嘛，是每一个说话者单独分开的，但是我看原论文里面，作者们好像是创建了混合语音来训练的吧。
> 
> 同学，我也是毕设做语音分离的，想问一下你的tensorflow用的什么版本的？是GPU版的吗？为什么我用GPU版本的报错。

你不改代码的话0 0   tf要用0.11      建议改一下代码，就可以移到py3和tf1.12上。

**Comment by JayYang-Fdu** [comment]
> 是的，我当时就是一个个产生的
> On 04/10/2019 16:22, Yangjie55 wrote:
> 哥 我又来了。。。希望没打扰到你。。。
> 就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing) 一个一个产生好像也可以，也不是很多。。。这个方法对吗?
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 哥，抱歉又要打扰你啦。这段时间我的程序已经能够分离出语音啦，但是我有几个问题，能请教你一下嘛：
> 1.因为聚类不是无监督学习嘛，那为啥这个需要创建这个lstm的神经网络来训练呢？（原论文只是随口提了一下深度学习获得嵌入特征能够使分离更高效，这里就不是很明白。。）还有就是那个spectral embedding不是很明白是啥意思，有点不太明白唉
> 2.还有一个问题就是，我用的数据集是timit数据集嘛，是每一个说话者单独分开的，但是我看原论文里面，作者们好像是创建了混合语音来训练的吧。
> 
> 
> 他这个是有监督的训练。embedding就是每个时频单元的D维特征.
> datagenerator.py就是用来将多个单人混合成多个双人的。
哇 谢谢解答！
datagenerator里定义的那个reinit函数吗 最终生成的pkl文件就是混合语音特征是的嘛？
可是深度聚类不是无监督训练吗？ 为啥是有监督的训练呀？我看论文里面好像也没有提及唉。。。具体是在哪里描述的呀。。。抱歉我是个小白。。。

**Comment by sTarAnna** [comment]
> > 是的，我当时就是一个个产生的
> > On 04/10/2019 16:22, Yangjie55 wrote:
> > 哥 我又来了。。。希望没打扰到你。。。
> > 就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing) 一个一个产生好像也可以，也不是很多。。。这个方法对吗?
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub, or mute the thread.
> > 哥，抱歉又要打扰你啦。这段时间我的程序已经能够分离出语音啦，但是我有几个问题，能请教你一下嘛：
> > 1.因为聚类不是无监督学习嘛，那为啥这个需要创建这个lstm的神经网络来训练呢？（原论文只是随口提了一下深度学习获得嵌入特征能够使分离更高效，这里就不是很明白。。）还有就是那个spectral embedding不是很明白是啥意思，有点不太明白唉
> > 2.还有一个问题就是，我用的数据集是timit数据集嘛，是每一个说话者单独分开的，但是我看原论文里面，作者们好像是创建了混合语音来训练的吧。
> > 他这个是有监督的训练。embedding就是每个时频单元的D维特征.
> > datagenerator.py就是用来将多个单人混合成多个双人的。
> > 哇 谢谢解答！
> > datagenerator里定义的那个reinit函数吗 最终生成的pkl文件就是混合语音特征是的嘛？
> > 可是深度聚类不是无监督训练吗？ 为啥是有监督的训练呀？我看论文里面好像也没有提及唉。。。具体是在哪里描述的呀。。。抱歉我是个小白。。。

1. 他的标签（label，target）生成是在原文3.2节一开始描述的，你仔细看一看0 0
2. 是

**Comment by JayYang-Fdu** [comment]
对呀 这里我就不是很明白 为啥...是有监督训练唉...发自我的华为手机-------- 原始邮件 --------主题：Re: [zhr1201/deep-clustering] the seperated speech can't play (#18)发件人：sTarAnna 收件人：zhr1201/deep-clustering 抄送：Yangjie55 ,Author 

是的，我当时就是一个个产生的
On 04/10/2019 16:22, Yangjie55 wrote:
哥 我又来了。。。希望没打扰到你。。。
就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing) 一个一个产生好像也可以，也不是很多。。。这个方法对吗?
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
哥，抱歉又要打扰你啦。这段时间我的程序已经能够分离出语音啦，但是我有几个问题，能请教你一下嘛：
1.因为聚类不是无监督学习嘛，那为啥这个需要创建这个lstm的神经网络来训练呢？（原论文只是随口提了一下深度学习获得嵌入特征能够使分离更高效，这里就不是很明白。。）还有就是那个spectral embedding不是很明白是啥意思，有点不太明白唉
2.还有一个问题就是，我用的数据集是timit数据集嘛，是每一个说话者单独分开的，但是我看原论文里面，作者们好像是创建了混合语音来训练的吧。
他这个是有监督的训练。embedding就是每个时频单元的D维特征.
datagenerator.py就是用来将多个单人混合成多个双人的。
哇 谢谢解答！
datagenerator里定义的那个reinit函数吗 最终生成的pkl文件就是混合语音特征是的嘛？
可是深度聚类不是无监督训练吗？ 为啥是有监督的训练呀？我看论文里面好像也没有提及唉。。。具体是在哪里描述的呀。。。抱歉我是个小白。。。


他的标签（label，target）生成是在原文3.2节一开始描述的，你仔细看一看0 0是

**Comment by zhr1201** [comment]
因为有label 哪些频点属于一个人的




On 04/24/2019 19:44, Yangjie55 wrote:
对呀 这里我就不是很明白 为啥...是有监督训练唉...发自我的华为手机-------- 原始邮件 --------主题：Re: [zhr1201/deep-clustering] the seperated speech can't play (#18)发件人：sTarAnna 收件人：zhr1201/deep-clustering 抄送：Yangjie55 ,Author

是的，我当时就是一个个产生的
On 04/10/2019 16:22, Yangjie55 wrote:
哥 我又来了。。。希望没打扰到你。。。
就是 我用的是你之前用的那个timit数据集，然后在train的文件夹里有dr1...dr8,每个文件夹里面都有不同的人说话的语音，那我怎么去产生pkl_list文件呢？一个一个产生吗？你回答别人的那个回答我没看懂唉（尴尬ing) 一个一个产生好像也可以，也不是很多。。。这个方法对吗?
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.
哥，抱歉又要打扰你啦。这段时间我的程序已经能够分离出语音啦，但是我有几个问题，能请教你一下嘛：
1.因为聚类不是无监督学习嘛，那为啥这个需要创建这个lstm的神经网络来训练呢？（原论文只是随口提了一下深度学习获得嵌入特征能够使分离更高效，这里就不是很明白。。）还有就是那个spectral embedding不是很明白是啥意思，有点不太明白唉
2.还有一个问题就是，我用的数据集是timit数据集嘛，是每一个说话者单独分开的，但是我看原论文里面，作者们好像是创建了混合语音来训练的吧。
他这个是有监督的训练。embedding就是每个时频单元的D维特征.
datagenerator.py就是用来将多个单人混合成多个双人的。
哇 谢谢解答！
datagenerator里定义的那个reinit函数吗 最终生成的pkl文件就是混合语音特征是的嘛？
可是深度聚类不是无监督训练吗？ 为啥是有监督的训练呀？我看论文里面好像也没有提及唉。。。具体是在哪里描述的呀。。。抱歉我是个小白。。。


他的标签（label，target）生成是在原文3.2节一开始描述的，你仔细看一看0 0是

**Comment by tangchenjun** [comment]
您好，请问最后分离的语音的评价指标也就是SDR，是怎么计算出来的啊？为什么我用matlab的工具箱bss_eval_sources计算出来是负数？而且是负十几😭

**Comment by sTarAnna** [comment]
> 您好，请问最后分离的语音的评价指标也就是SDR，是怎么计算出来的啊？为什么我用matlab的工具箱bss_eval_sources计算出来是负数？而且是负十几😭

https://github.com/jacoxu/ASAM/blob/master/software/predict.py 这里边有

**Comment by JayYang-Fdu** [comment]
我又来了。。。 我想问一下就是关于accuracy的问题，模型输出的embedding是【12800，129，40】的维度，但是预测值Y-data的维度是【12800，129，2】这两个维度不一样啊，我做accuracy的时候，这两个怎么同纬度呢？

**Comment by njusq** [comment]
> 我又来了。。。 我想问一下就是关于accuracy的问题，模型输出的embedding是【12800，129，40】的维度，但是预测值Y-data的维度是【12800，129，2】这两个维度不一样啊，我做accuracy的时候，这两个怎么同纬度呢？

embedding是把混合语音的谱映射到更高维度的结果，Y是二值掩蔽，它俩所表示的就不是一个东西，不能直接拿它俩做accuracy的。如果要评估这个模型，文献上是计算SDRi，这里的code貌似没有那一步。

**Comment by sTarAnna** [comment]
> 我又来了。。。 我想问一下就是关于accuracy的问题，模型输出的embedding是【12800，129，40】的维度，但是预测值Y-data的维度是【12800，129，2】这两个维度不一样啊，我做accuracy的时候，这两个怎么同纬度呢？

调matlab的bss_eval 工具箱

**Comment by sTarAnna** [comment]
> 我又来了。。。 我想问一下就是关于accuracy的问题，模型输出的embedding是【12800，129，40】的维度，但是预测值Y-data的维度是【12800，129，2】这两个维度不一样啊，我做accuracy的时候，这两个怎么同纬度呢？

而且Y-data是mask,emb还需要做聚类才能生成mask。你再看看论文，用的是SDRi ，SDR就用matlab的bss_eval

**Comment by JayYang-Fdu** [comment]
> 我又来了。。。 我想问一下就是关于accuracy的问题，模型输出的embedding是【12800，129，40】的维度，但是预测值Y-data的维度是【12800，129，2】这两个维度不一样啊，我做accuracy的时候，这两个怎么同纬度呢？
> 
> 而且Y-data是mask,emb还需要做聚类才能生成mask。你再看看论文，用的是SDRi ，SDR就用matlab的bss_eval

好吧。。。谢谢大家的解答，其实我看了论文但是很多地方不明白，我做这个方向主要是因为我本科毕设的题目是这个，然后一直在弄这个，实验室也没有人做语音分离的内容，就一个人自己一边上课，一边琢磨这个虽然自己浪费了很多时间，。。，自己看了又不怎么理解里面很多专有名词的意思，就一直都很懵。给大家带来了麻烦，很抱歉！同时很感谢大家的解答...虽然还是很不懂语音这方面的东西，不过还是学到了很多。

**Comment by Yangjie55** [comment]
> > 我又来了。。。 我想问一下就是关于accuracy的问题，模型输出的embedding是【12800，129，40】的维度，但是预测值Y-data的维度是【12800，129，2】这两个维度不一样啊，我做accuracy的时候，这两个怎么同纬度呢？
> 
> 而且Y-data是mask,emb还需要做聚类才能生成mask。你再看看论文，用的是SDRi ，SDR就用matlab的bss_eval

。。。我又来了。。。那个ＳＤＲ怎么生成，不知道怎么用ＭＡＴＬＡＢ的bss_eval的工具箱怎么用啊。。。。。你可以把我当个弱智来对待。。因为真的一点不明白（捂脸０．０）
https://github.com/jacoxu/ASAM/blob/master/software/predict.py 这页的代码，然后我是要自己写脚本去调用这些个函数吗？还是怎么弄的呀...

**Comment by JayYang-Fdu** [comment]
> 您好，请问最后分离的语音的评价指标也就是SDR，是怎么计算出来的啊？为什么我用matlab的工具箱bss_eval_sources计算出来是负数？而且是负十几😭

你是不是把分离的语音作为那个代码的输入了？我把分离出来的语音作为输入，也得到了负十几。。。你是把什么当作输入的呀

**Comment by yzy0729** [comment]
> 这个看上去是在-1到1之间的，有些就算超过了也会clip掉的，应该是写wav的库版本和之前的有些不同。你看看那个模块（记得好像是librosa）音频读写的说明就行了



> > by the way你哪个学校什么专业的啊？本科毕设？
> 
> 对的，做的是本科毕设，我本科上海大学，做的题目是基于深度学习的语音信号分离...以前从来没接触过深度学习，唉眼看着要答辩了...心态不能崩hhh。那个数组我截的图如下：
> ![image](https://user-images.githubusercontent.com/48006476/55786041-13a3f180-5ae6-11e9-8d8c-a5007ae3fbe0.png)
> 
> 这个是分离出audio_out1 数组 好像不在-1到1 之间。。。

你好同学，请问你分离出来的语音可以播放了吗？我在电脑上也播不出来，说是编码格式不受用，请问这个怎么解决呢？

**Comment by sTarAnna** [comment]
> > 您好，请问最后分离的语音的评价指标也就是SDR，是怎么计算出来的啊？为什么我用matlab的工具箱bss_eval_sources计算出来是负数？而且是负十几😭
> 
> 你是不是把分离的语音作为那个代码的输入了？我把分离出来的语音作为输入，也得到了负十几。。。你是把什么当作输入的呀



> > 您好，请问最后分离的语音的评价指标也就是SDR，是怎么计算出来的啊？为什么我用matlab的工具箱bss_eval_sources计算出来是负数？而且是负十几😭
> 
> 你是不是把分离的语音作为那个代码的输入了？我把分离出来的语音作为输入，也得到了负十几。。。你是把什么当作输入的呀

`            s0 , _ = librosa.load(data_dir +str(i1)+ '/out_.wav', 8000)
            s1 , _ = librosa.load(data_dir+str(i1)+ '/speech_1.wav', 8000)
            s2 , _ = librosa.load(data_dir +str(i1)+ '/speech_2.wav', 8000)
            l1 = np.min([len(s1),len(s2),len(out_audio1),len(out_audio2),len(s0)])
            s1 = s1[:l1]
            s2 = s2[:l1]
            out_audio1=out_audio1[:l1]
            out_audio2=out_audio2[:l1]
            s0 = s0[:l1]
            res0, res1 = matlabeng.bss_eval_sources(matlab.double([s0.tolist(), s0.tolist()]),
                                                   matlab.double([s1.tolist(), s2.tolist()]))

            res2,res3=matlabeng.bss_eval_sources(matlab.double([out_audio1.tolist(),out_audio2.tolist()]),matlab.double([s1.tolist(),s2.tolist()]))
            lsdri=(res2[0]-res0[0]+res3[0]-res1[0])/2
            ressdri=ressdri+lsdri`

丑陋的代码。参考一下就行

**Comment by sTarAnna** [comment]
> > 您好，请问最后分离的语音的评价指标也就是SDR，是怎么计算出来的啊？为什么我用matlab的工具箱bss_eval_sources计算出来是负数？而且是负十几😭
> 
> 你是不是把分离的语音作为那个代码的输入了？我把分离出来的语音作为输入，也得到了负十几。。。你是把什么当作输入的呀


```
s0 , _ = librosa.load(data_dir +str(i1)+ '/out_.wav', 8000)
s1 , _ = librosa.load(data_dir+str(i1)+ '/speech_1.wav', 8000)
s2 , _ = librosa.load(data_dir +str(i1)+ '/speech_2.wav', 8000)
l1 = np.min([len(s1),len(s2),len(out_audio1),len(out_audio2),len(s0)])
s1 = s1[:l1]
s2 = s2[:l1]
out_audio1=out_audio1[:l1]
out_audio2=out_audio2[:l1]
s0 = s0[:l1]
res0, res1 = matlabeng.bss_eval_sources(matlab.double([s0.tolist(), s0.tolist()]),
                                       matlab.double([s1.tolist(), s2.tolist()]))

res2,res3=matlabeng.bss_eval_sources(matlab.double([out_audio1.tolist(),out_audio2.tolist()]),matlab.double([s1.tolist(),s2.tolist()]))
lsdri=(res2[0]-res0[0]+res3[0]-res1[0])/2
ressdri=ressdri+lsdri
```
丑陋的代码，参考下就行。

**Comment by sTarAnna** [comment]
> > 这个看上去是在-1到1之间的，有些就算超过了也会clip掉的，应该是写wav的库版本和之前的有些不同。你看看那个模块（记得好像是librosa）音频读写的说明就行了
> 
> > > by the way你哪个学校什么专业的啊？本科毕设？
> > 
> > 
> > 对的，做的是本科毕设，我本科上海大学，做的题目是基于深度学习的语音信号分离...以前从来没接触过深度学习，唉眼看着要答辩了...心态不能崩hhh。那个数组我截的图如下：
> > ![image](https://user-images.githubusercontent.com/48006476/55786041-13a3f180-5ae6-11e9-8d8c-a5007ae3fbe0.png)
> > 这个是分离出audio_out1 数组 好像不在-1到1 之间。。。
> 
> 你好同学，请问你分离出来的语音可以播放了吗？我在电脑上也播不出来，说是编码格式不受用，请问这个怎么解决呢？

在Linux上播放。

**Comment by yzy0729** [comment]
今天问了组了的师兄，可以用matlab先把.wav文件一读，然后sound再写出来。因为原始语音是256kbps(16位每个码)，用librosa生成的是512kbps(32位)，所以windows放不了，这样生成的.wav文件就可以用windows播放出来了。



------------------ Original ------------------

**Comment by yzy0729** [comment]
> > > 您好，请问最后分离的语音的评价指标也就是SDR，是怎么计算出来的啊？为什么我用matlab的工具箱bss_eval_sources计算出来是负数？而且是负十几😭
> > 
> > 
> > 你是不是把分离的语音作为那个代码的输入了？我把分离出来的语音作为输入，也得到了负十几。。。你是把什么当作输入的呀
> 
> ```
> s0 , _ = librosa.load(data_dir +str(i1)+ '/out_.wav', 8000)
> s1 , _ = librosa.load(data_dir+str(i1)+ '/speech_1.wav', 8000)
> s2 , _ = librosa.load(data_dir +str(i1)+ '/speech_2.wav', 8000)
> l1 = np.min([len(s1),len(s2),len(out_audio1),len(out_audio2),len(s0)])
> s1 = s1[:l1]
> s2 = s2[:l1]
> out_audio1=out_audio1[:l1]
> out_audio2=out_audio2[:l1]
> s0 = s0[:l1]
> res0, res1 = matlabeng.bss_eval_sources(matlab.double([s0.tolist(), s0.tolist()]),
>                                        matlab.double([s1.tolist(), s2.tolist()]))
> 
> res2,res3=matlabeng.bss_eval_sources(matlab.double([out_audio1.tolist(),out_audio2.tolist()]),matlab.double([s1.tolist(),s2.tolist()]))
> lsdri=(res2[0]-res0[0]+res3[0]-res1[0])/2
> ressdri=ressdri+lsdri
> ```
> 
> 丑陋的代码，参考下就行。

你好，请问你代码里的matlabeng是什么呢？

**Comment by sTarAnna** [comment]
> > > > 您好，请问最后分离的语音的评价指标也就是SDR，是怎么计算出来的啊？为什么我用matlab的工具箱bss_eval_sources计算出来是负数？而且是负十几😭
> > > 
> > > 
> > > 你是不是把分离的语音作为那个代码的输入了？我把分离出来的语音作为输入，也得到了负十几。。。你是把什么当作输入的呀
> > 
> > 
> > ```
> > s0 , _ = librosa.load(data_dir +str(i1)+ '/out_.wav', 8000)
> > s1 , _ = librosa.load(data_dir+str(i1)+ '/speech_1.wav', 8000)
> > s2 , _ = librosa.load(data_dir +str(i1)+ '/speech_2.wav', 8000)
> > l1 = np.min([len(s1),len(s2),len(out_audio1),len(out_audio2),len(s0)])
> > s1 = s1[:l1]
> > s2 = s2[:l1]
> > out_audio1=out_audio1[:l1]
> > out_audio2=out_audio2[:l1]
> > s0 = s0[:l1]
> > res0, res1 = matlabeng.bss_eval_sources(matlab.double([s0.tolist(), s0.tolist()]),
> >                                        matlab.double([s1.tolist(), s2.tolist()]))
> > 
> > res2,res3=matlabeng.bss_eval_sources(matlab.double([out_audio1.tolist(),out_audio2.tolist()]),matlab.double([s1.tolist(),s2.tolist()]))
> > lsdri=(res2[0]-res0[0]+res3[0]-res1[0])/2
> > ressdri=ressdri+lsdri
> > ```
> > 
> > 
> > 丑陋的代码，参考下就行。
> 
> 你好，请问你代码里的matlabeng是什么呢？

```
import matlab.engine
matlabeng = matlab.engine.start_matlab()
```

python调matlab你百度一下0 0
