### ISSUE TITLE
Could you provide a pre-trained model for testing?

### ISSUE THREAD

**Issue by NewEricWang** [zhr1201/deep-clustering#23]
Hi,
     I want to know whether the method is applied to my project. So I can test the performance by my test data. Could you provide a pre-trained model for my testing?

**Comment by zhr1201** [comment]
Unfortunately, that is not possible cause it is written a long time ago and and didn't backup the model myself.

**Comment by NewEricWang** [comment]
Ok! Thank you  very much!
