### ISSUE TITLE
Where are the pkl_list defined in the train_net.py?

### ISSUE THREAD

**Issue by Jingqiao-Hu** [zhr1201/deep-clustering#9]
Where are the pkl_list defined in the train_net.py?
`pkl_list = ['../dcdata/' + str(i) + '.pkl' for i in range(1, 12)]`

I just got one val.pkl generated in datagenerator.py
`cPickle.dump(self.samples, open('val.pkl', 'wb'))`

**Comment by jan-bk** [comment]
I am having the same problem. Could you tell me how you solved it? Or am I misunderstanding something? Thank you.
